---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthapp-deploy
  labels:
    app: healthcare-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: healthcare-app
  template:
    metadata:
      labels:
        app: healthcare-app
    spec:
      containers:
        - name: healthcare-app-container
          image: urvi11umesh/healthcare-app
          ports:
            - containerPort: 8082

---
apiVersion: v1
kind: Service
metadata:
  name: healthcare-np-service
  labels:
    app: healthcare-app
spec:
  selector:
    app: healthcare-app
  type: NodePort
  ports:
    - port: 8082
      targetPort: 8082
      nodePort: 
